version: "3.8"

services:

  crypto_mongo_db:
    image: mongo:latest
    container_name: crypto_mongo_db
    env_file:
      - ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
  app:
    depends_on:
      - crypto_mongo_db
    build: .
    image: antp/crypto_mongodb
    env_file:
      - ./.env
    environment:
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=$MONGODB_DATABASE
      - SPRING_DATA_MONGODB_DATABASE=$MONGODB_DATABASE
      - SPRING_DATA_MONGODB_HOST=$MONGODB_HOST
      - SPRING_DATA_MONGODB_PORT=$MONGODB_DOCKER_PORT
      - logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    links:
      - crypto_mongo_db
